### ISSUE TITLE
How to compile noise.js file ?

### ISSUE THREAD

**Issue by iamblue** [jmvalin/rnnoise_demo#15]
As title , It seem compile by Webassembly ? Could you share the way to do this ? Thanks ~

**Comment by mbebenita** [comment]
Last I tried this, I used

```
emcc src/denoise.c src/rnn.c src/rnn_data.c src/pitch.c src/kiss_fft.c src/celt_lpc.c -Isrc -Iinclude -O3 -o noise.js -s TOTAL_MEMORY=134217728 -s MODULARIZE=1 -s EXPORT_NAME="'NoiseModule'" --memory-init-file 0
```

You'll have to install [Emscripten](http://kripken.github.io/emscripten-site/)  first.

**Comment by iamblue** [comment]
Thanks!

**Comment by vishaldhull09** [comment]
@iamblue @mbebenita  any idea how can we access the original model file (.hdf5)

**Comment by vishaldhull09** [comment]
> Last I tried this, I used
> 
> ```
> emcc src/denoise.c src/rnn.c src/rnn_data.c src/pitch.c src/kiss_fft.c src/celt_lpc.c -Isrc -Iinclude -O3 -o noise.js -s TOTAL_MEMORY=134217728 -s MODULARIZE=1 -s EXPORT_NAME="'NoiseModule'" --memory-init-file 0
> ```
> 
> You'll have to install [Emscripten](http://kripken.github.io/emscripten-site/) first.
@mbebenita @jmvalin @yurydelendik 
I also tried same command but noise.js file produced is very much different, there are weight values inside in original noise.js but not in file produced by this command. if you are seeing this , please reply it's urgent.
Thanks
